version: '3'

services:
  mediawiki:
    image: 'sumeetpanse/hackathonapp:1.1'
    entrypoint: bash -c "/app-entrypoint.sh httpd -f /bitnami/apache/conf/httpd.conf;sleep 20;git clone https://sumeetpanse%40gmail.com:SPdoc%406177@github.com/spdoc/InfyWiki.git;cp -r /InfyWiki/app/images/* /bitnami/mediawiki/images;cp -r /InfyWiki/app/skins/* /bitnami/mediawiki/skins/;cp -r /InfyWiki/app/extensions/* /bitnami/mediawiki/extensions/;cp /InfyWiki/app/wiki.png /bitnami/mediawiki/images/;mv /bitnami/mediawiki/LocalSettings.php /bitnami/mediawiki/LocalSettings.php.bkp;mv /InfyWiki/app/LocalSettings1.php /InfyWiki/app/LocalSettings.php;mv /InfyWiki/app/LocalSettings.php /bitnami/mediawiki/;while :; do sleep 1; done"
    ports:
      - '80:80'
      - '443:443'
    environment:
      - MARIADB_HOST=hackathon.cczyokw5e7jg.ap-south-1.rds.amazonaws.com
      - MARIADB_PORT_NUMBER=3306
      - MEDIAWIKI_DATABASE_USER=bn_mediawiki
      - MEDIAWIKI_DATABASE_NAME=bitnami_mediawiki
      - MEDIAWIKI_DATABASE_PASSWORD=bn_mediawiki
    volumes:
      - 'web1:/bitnami'
    logging:
      driver: awslogs
      options:
        awslogs-group: InfyWiki_app
        awslogs-region: ap-south-1
        awslogs-stream-prefix: wikiapp
  jenkins:
    image: 'sumeetpanse/jenkin:1.4'
    command: bash -c "git clone https://github.com/spdoc/mysql.git;mv mysql/jenkins_home/* /var/jenkins_home;echo 'admin' > /var/jenkins_home/jenkins-user;echo 'admin' > /var/jenkins_home/jenkins-pass;/sbin/tini -- /usr/local/bin/jenkins.sh;"
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - 'jenkins1:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    logging:
      driver: awslogs
      options:
        awslogs-group: InfyWiki_Jenkins
        awslogs-region: ap-south-1
        awslogs-stream-prefix: wikijenkin
volumes:
  web1:
  jenkins1:
